commands = [
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the orange square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the orange square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the orange square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle.",
    "Click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the orange square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink square.",
    "Click on the red square.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the blue wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square.",
    "Click on the red square.",
    "Click on the red wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the red square.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the pink square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue square.",
    "Click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the pink square.",
    "Click on the green square.",
    "Click on the blue square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the green square.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the yellow wide rectangle and then click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue square and then click on the red square.",
    "Click on the orange square and then click on the blue square.",
    "Click on the blue square and then click on the green wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the blue wide rectangle and then click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink wide rectangle and then click on the yellow wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow square and then click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the orange square and then click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the red wide rectangle and then click on the orange square.",
    "Click on the yellow wide rectangle.",
    "Click on the orange square.",
    "Click on the orange wide rectangle and then click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the red square and then click on the orange square.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the red square.",
    "Click on the blue square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue square and then click on the red square.",
    "Click on the pink square and then click on the green wide rectangle.",
    "Click on the yellow square and then click on the orange square.",
    "Click on the orange wide rectangle and then click on the blue square.",
    "Click on the green square.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the pink wide rectangle and then click on the pink square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle and then click on the blue square.",
    "Click on the pink square.",
    "Click on the yellow square.",
    "Click on the orange square and then click on the pink square.",
    "Click on the yellow square.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the green square and then click on the pink wide rectangle.",
    "Click on the yellow wide rectangle and then click on the red wide rectangle.",
    "Click on the yellow wide rectangle and then click on the blue wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the blue square and then click on the orange square.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the pink wide rectangle and then click on the red square.",
    "Click on the pink wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square.",
    "Click on the red square.",
    "Click on the red wide rectangle and then click on the green wide rectangle.",
    "Click on the blue square and then click on the yellow wide rectangle.",
    "Click on the pink square and then click on the orange square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the green square and then click on the green wide rectangle.",
    "Click on the orange wide rectangle and then click on the yellow square.",
    "Click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the blue square and then click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle and then click on the pink wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the blue square and then click on the yellow wide rectangle.",
    "Click on the green wide rectangle and then click on the yellow square.",
    "Click on the blue wide rectangle.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the orange wide rectangle.",
    "Click on the yellow square and then click on the orange square.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square and then click on the green square.",
    "Click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the green wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the yellow wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the orange wide rectangle and then click on the yellow wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the orange square and then click on the pink square.",
    "Click on the yellow square and then click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the pink square.",
    "Click on the green wide rectangle.",
    "Click on the red wide rectangle and then click on the orange wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the red square and then click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the red square and then click on the pink wide rectangle.",
    "Click on the green square and then click on the yellow square.",
    "Click on the green square.",
    "Click on the green wide rectangle and then click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the pink square and then click on the green square.",
    "Click on the orange square and then click on the red square.",
    "Click on the red square.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the blue square.",
    "Click on the pink wide rectangle and then click on the blue square.",
    "Click on the green square and then click on the yellow wide rectangle.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the green square and then click on the yellow square.",
    "Click on the green wide rectangle and then click on the orange wide rectangle.",
    "Click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square and then click on the blue square.",
    "Click on the orange square and then click on the orange wide rectangle.",
    "Click on the blue square.",
    "Click on the red square and then click on the green square.",
    "Click on the yellow wide rectangle and then click on the blue square.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the pink wide rectangle and then click on the blue wide rectangle.",
    "Click on the blue square.",
    "Click on the blue square and then click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the red square and then click on the orange wide rectangle.",
    "Click on the red square.",
    "Click on the pink square.",
    "Click on the orange wide rectangle and then click on the red square.",
    "Click on the green wide rectangle and then click on the yellow square.",
    "Click on the red wide rectangle and then click on the yellow wide rectangle.",
    "Click on the green wide rectangle.",
    "Click on the yellow wide rectangle and then click on the blue square.",
    "Click on the pink square.",
    "Click on the red square and then click on the orange square.",
    "Click on the red square.",
    "Click on the yellow square.",
    "Click on the orange wide rectangle and then click on the orange square.",
    "Click on the yellow square.",
    "Click on the pink square.",
    "Click on the red wide rectangle.",
    "Click on the red square.",
    "Click on the red square and then click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the pink square and then click on the pink wide rectangle.",
    "Click on the blue wide rectangle and then click on the green wide rectangle.",
    "Click on the pink wide rectangle.",
    "Click on the yellow square.",
    "Click on the orange square and then click on the orange wide rectangle.",
    "Click on the blue wide rectangle and then click on the green square.",
    "Click on the red wide rectangle.",
    "Click on the green wide rectangle and then click on the green square.",
    "Click on the pink square.",
    "Click on the yellow square and then click on the blue wide rectangle.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the yellow square and then click on the yellow wide rectangle.",
    "Click on the orange wide rectangle.",
    "Click on the blue wide rectangle and then click on the yellow wide rectangle.",
    "Click on the blue square and then click on the red square.",
    "Click on the orange square.",
    "Click on the red wide rectangle.",
    "Click on the blue wide rectangle.",
    "Click on the green wide rectangle and then click on the orange square.",
    "Click on the pink wide rectangle.",
    "Click on the orange wide rectangle and then click on the blue wide rectangle.",
    "Click on the blue wide rectangle and then click on the blue square.",
    "Click on the orange wide rectangle and then click on the yellow square.",
    "Click on the green wide rectangle.",
    "Click on the yellow square.",
    "Click on the blue wide rectangle and then click on the orange square.",
    "Click on the yellow wide rectangle and then click on the green square.",
    "Click on the pink wide rectangle.",
    "Click on the red wide rectangle.",
    "Click on the green square and then click on the red square.",
    "Click on the yellow wide rectangle.",
    "Click on the green square and then click on the blue wide rectangle.",
    "Click on the pink square and then click on the blue square.",
    "Click on the orange square.",
    "Click on the blue wide rectangle.",
    "Click on the pink square and then click on the red square.",
    "Click on the blue square.",
    "Click on the red wide rectangle.",
    "Click on the orange square.",
    "Click on the blue square.",
    "Click on the pink square.",
]

position = {
    "red square" : (76, 81),
    "yellow square" : (181, 88),
    "red wide rectangle" : (295, 79),
    "yellow wide rectangle" : (507, 80),
    "green square" : (72, 181),
    "orange square" : (164, 182),
    "green wide rectangle" : (306, 181),
    "orange wide rectangle" : (507, 177),
    "blue square" : (76, 286),
    "pink square" : (180, 284),
    "blue wide rectangle" : (294, 275),
    "pink wide rectangle" : (489, 280)
}

for command in commands:
    tokens = command[:-1].split(" ")
    color1 = tokens[3]
    shape1 = tokens[4]
    if shape1 == "wide":
        shape1 += " " + tokens[5]
    pos1 = position[color1 + " " + shape1]
    print pos1[0], pos1[1]
    if len(tokens) > 6:
        shape2 = tokens[-1]
        if shape2 == "rectangle":
            shape2 = tokens[-2] + " " + shape2
            color2 = tokens[-3]
        else:
            color2 = tokens[-2]
        pos2 = position[color2 + " " + shape2]
        print pos2[0], pos2[1]
    print "next"

print "done"
